export const categories = [
  {
    title: 'Intro',
    description:
      'A beginner-friendly introduction to the Go programming language.',
    link: '/intro',
  },
  {
    title: 'Setting Up Environment',
    description: 'Learn how to get your Go development environment ready.',
    link: '/setting-up-environment',
  },
  {
    title: 'Variables and Types',
    description: "Understand Go's data types and how to declare variables.",
    link: '/variables-and-types',
  },
  {
    title: 'Functions',
    description: 'Define reusable blocks of code in Go',
    link: '/functions',
  },
  {
    title: 'Structs',
    description: 'Create custom data structures in Go.',
    link: '/structs',
  },
  {
    title: 'Interfaces',
    description: 'Define contracts for behavior, promoting code flexibility.',
    link: '/interfaces',
  },
  {
    title: 'Errors',
    description: 'Handle errors gracefully in Go.',
    link: '/errors',
  },
  {
    title: 'Loops',
    description: 'Iterate over sequences of data in Go.',
    link: '/loops',
  },
  {
    title: 'Slices',
    description: 'Dynamic arrays in Go.',
    link: '/slices',
  },
  {
    title: 'Maps',
    description: 'Key-value pairs for efficient data storage.',
    link: '/maps',
  },
  {
    title: 'Advanced Functions',
    description: "Explore Go's more complex function features.",
    link: '/advanced-functions',
  },
  {
    title: 'Channels',
    description: 'Communicate between goroutines safely and concurrently.',
    link: '/channels',
  },
  {
    title: 'Mutexes',
    description: ' Protect shared data from race conditions.',
    link: '/mutexes',
  },
  {
    title: 'Generics',
    description: 'Write reusable and type-safe code with generics in Go.',
    link: '/generics',
  },
  {
    title: 'Go Facts',
    description: 'Additional concepts and Go proverbs',
    link: '/go-facts',
  },
];

export const topics = {
  intro: [
    'go-introduction',
    'compiling',
    'compiled-vs-interpreted',
    'go-memory-usage',
    'go-is-strongly-typed',
    'wrapping-up',
  ],
  setting_up_environment: [
    'installing-go-tools',
    'packages',
    'modules',
    'your-first-go-program',
    'go-tooling',
    'choose-your-tools',
    'wrapping-up',
  ],
  variables_and_types: [
    'basic-types',
    'type-inference',
    'type-sizes',
    'constants',
    'formatting-strings',
    'conditionals',
    'wrapping-up',
  ],
  functions: [
    'intro',
    'declaration-syntax',
    'return-values',
    'named-returns',
    'benefits-of-named-returns',
    'early-returns',
    'wrapping-up',
  ],
  structs: [
    'structs-in-go',
    'nested-structs',
    'anonymous-structs',
    'embedded-structs',
    'struct-methods',
    'wrapping-up',
  ],
  interfaces: [
    'interfaces-in-go',
    'multiple-interfaces',
    'type-assertion',
    'clean-interfaces',
    'wrapping-up',
  ],
  errors: [
    'the-error-interface',
    'formatting-strings',
    'custom-errors',
    'the-errors-package',
    'wrapping-up',
  ],
  loops: [
    'intro',
    'omitting-conditions',
    'while-loop',
    'operators',
    'continue-and-break',
    'wrapping-up',
  ],
  slices: [
    'arrays',
    'slices-in-go',
    'slices-review',
    'make-function',
    'len-and-cap-review',
    'variadic-functions',
    'slice-gotcha',
    'wrapping-up',
  ],
  maps: [
    'maps-in-go',
    'mutating-maps',
    'key-types',
    'nested-maps',
    'maps-review',
    'wrapping-up',
  ],
  advanced_functions: [
    'higher-order-functions',
    'why-higher-order-functions',
    'currying',
    'defer',
    'closures',
    'anonymous-functions',
    'pointers-intro',
    'pointer-receivers',
    'wrapping-up',
  ],
};
